version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Trigger Pipeline
          command: |
            response=$(curl -s -X POST https://circleci.com/api/v2/project/github/AndriiFrolov/playwright-circleci-allure/pipeline \
              --header "Circle-Token: CCIPAT_BUMzyWpfgC9fkudmkjKhZj_040bce6997b19ae833da6ca01db8931d6f4e3aef" \
              --header "Content-Type: application/json" \
              --data '{"branch": "master", "parameters": {"CIRCLE_SHA1": "'$CIRCLE_SHA1'"}}')

#            pipeline_id=$(echo "$response" | jq -r '.id')
#
#            start_time=$(date +%s)
#            timeout=60  # 1 minute timeout
#
#            while true; do
#              current_time=$(date +%s)
#              elapsed_time=$((current_time - start_time))
#
#              if [ "$elapsed_time" -ge "$timeout" ]; then
#                status_response=$(curl -s -X GET "https://circleci.com/api/v2/pipeline/$pipeline_id" \
#                  --header "Circle-Token: CCIPAT_BUMzyWpfgC9fkudmkjKhZj_040bce6997b19ae833da6ca01db8931d6f4e3aef")
#
#                current_status=$(echo "$status_response" | jq -r '.state')
#
#                if [ "$current_status" != "done" ]; then
#                  echo "Pipeline execution timed out after 1 minutes."
#                  exit 1
#                fi
#              fi
#
#              if [ "$current_status" = "done" ]; then
#                break
#              fi
#
#              sleep 5
#            done
#
#            echo "Pipeline execution is complete."
