version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Trigger Pipeline
          command: |
            response=$(curl -s -X POST https://circleci.com/api/v2/project/github/AndriiFrolov/playwright-circleci-allure/pipeline \
              --header "Circle-Token: CCIPAT_BUMzyWpfgC9fkudmkjKhZj_040bce6997b19ae833da6ca01db8931d6f4e3aef" \
              --header "Content-Type: application/json" \
              --data '{"branch": "master", "parameters": {"commit": "'$CIRCLE_SHA1'"}}')